### PR TITLE
fix init_prepare bug which may discard mutation, and fixes #41 rep_tests

### LINKED ISSUE #41: fix rep_test to make it work ok, and put it into hook checks

### PR DESCRIPTION
**Pull request by qinzuoyan**
fix rep_tests case-402, refer to https://github.com/imzhenyu/rDSN/issues/41

### CODE REVIEW

File: src/tests/mutation_log_learn.cpp [hunk 1]
```diff
@@ -138,7 +138,7 @@ TEST(replication, log_learn)
             ).end_tracking();
         auto time_toc = clock.now();
         
-        std::cout << "TEST replay time(us): " << std::chrono::duration_cast<std::chrono::microseconds>(time_toc - time_tic).count() << std::endl;
+        std::cout << "TEST replay time(ms): " << std::chrono::duration_cast<std::chrono::microseconds>(time_toc - time_tic).count() << std::endl;
```
Comment (imzhenyu) [inline src/tests/mutation_log_learn.cpp]: microseconds => us

File: src/apps/replication/lib/replica_config.cpp [hunk 2]
```diff
@@ -583,10 +583,13 @@ bool replica::update_local_configuration(const replica_configuration& config, bo
         switch (config.status)
         {
         case PS_PRIMARY:
+            {
             replay_prepare_list();
-            _primary_states.write_queue.check_possible_work(
+            mutation_ptr next = _primary_states.write_queue.check_possible_work(
```
Comment (imzhenyu) [inline src/apps/replication/lib/replica_config.cpp:588]: my bad - forget these places after API change

File: src/apps/replication/lib/mutation.cpp [hunk 3]
```diff
@@ -39,6 +39,8 @@
 
 namespace dsn { namespace replication {
 
+static std::atomic<uint64_t> s_mutation_tid(0);
```
Comment (imzhenyu) [inline src/apps/replication/lib/mutation.cpp]: good. it is better to place as mutation::s_tid;

Comment (qinzuoyan) [inline src/apps/replication/lib/mutation.cpp]: ok

File: src/tests/mutation_log_learn.cpp (hunk 1 above)
Comment (qinzuoyan) [inline src/tests/mutation_log_learn.cpp]: sure, because when I run log_learn test, it took a long time (about 30 seconds), so I thought maybe the timer is in ms. My fault, I should have look into it more carefully.
Now I find it's the writing step which takes so long a time, and I have improved it to less than 1 second.
btw, in mutation_log::flush(), the dsn_task_tracker_wait_all(tracker()) takes about 25ms to wait, is it reasonable? maybe we need test its performance and find out something wrong...
